# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


# Create an Account
POST localhost:8081/createAccount
Content-Type: application/json

{
  "name": "Florian"
}

###

# Get all Acc Numbers
GET localhost:8081/getAccountNumbers

###

# Get one Account
GET localhost:8081/getAccount?accnum=10fdc920-45dc-11e9-85f8-2d501bfa43ee

###

# Close an Account
PUT localhost:8081/closeAccount
Content-Type: application/json

{
  "accnum": "25224880-45e2-11e9-b0c8-cf868ac9c01a"
}

###

POST localhost:8081/deposit
Content-Type: application/json

{
  "accnum": "25224880-45e2-11e9-b0c8-cf868ac9c01a",
  "amount": 250
}

###

POST localhost:8081/withdraw
Content-Type: application/json

{
  "accnum": "25224880-45e2-11e9-b0c8-cf868ac9c01a",
  "amount": 100
}

###